### ISSUE TITLE
README 的声明与 MIT License 冲突

### ISSUE THREAD

**Issue by ouuan** [Naptie/BiliDownload#5]
> 本项目遵循 MIT 协议，修改或发布前须经本人同意；
>
> 本项目仅用于学习和测试，请勿滥用；

MIT 协议允许未经同意的修改或发布，也允许基于任何目的的使用。请修改该声明或不以 MIT 协议发布。但需要注意的是，在新版本中更换协议不影响老版本中的协议对老版本的代码生效。

**Comment by Naptie** [comment]
感谢提醒 XD
