### ISSUE TITLE
好棒，不过有个小问题，输入完整保存路径真的超累的

### ISSUE THREAD

**Issue by LemonNekoGH** [Naptie/BiliDownload#6]
*虽然已经有把保存路径存起来的功能了*

希望在输入保存路径时可以用 `~` 符号表示当前用户的家路径，谢谢啦w
#### 可以想到的大概的实现路径：
1. 通过 `java.lang.String.startsWith(String)` 来判断第一个字符是否是 `~`
2. 通过给 `java.lang.System.getProperty(String)` 方法传入 `user.home` 来获取当前用户的家路径
3. 拼接家路径和除 `~` 外剩余所有字符，得到完整路径

**Comment by Naptie** [comment]
这个可以有

**Comment by Naptie** [comment]
[1.3.6](https://github.com/Naptie/BiliDownload/releases/tag/v1.3.6) 中实现了
