### ISSUE TITLE
mac和linux下的ffmpeg的exe扩展名

### ISSUE THREAD

**Issue by niu541412** [Naptie/BiliDownload#7]
linux和macos上ffmpeg的可执行程序都是无后缀的
实测mac系统下载无问题。但是合并那个选项必须强制exe后缀。
可否修改兼容一下。
不太想修改文件名。
多谢~

**Comment by Naptie** [comment]
[1.3.6](https://github.com/Naptie/BiliDownload/releases/tag/v1.3.6) 中实现了。
